;;; npm-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from npm.el

(autoload 'npm "npm" "\
Entrypoint function to the package.
This will first check to make sure there is a package.json file and then open the menu." t)
(register-definition-prefixes "npm" '("npm-mode"))


;;; Generated autoloads from npm-common.el

(register-definition-prefixes "npm-common" '("npm-common-"))


;;; Generated autoloads from npm-init.el

(autoload 'npm-init "npm-init" "\
Initialize a project folder as a npm project." t)
(register-definition-prefixes "npm-init" '("npm-init--"))


;;; Generated autoloads from npm-install.el

(autoload 'npm-install "npm-install" "\
Invoke the compile mode with the install prefix-command and ARGS if provided.

(fn &optional ARGS)" t)
(register-definition-prefixes "npm-install" '("npm-install-"))


;;; Generated autoloads from npm-publish.el

(autoload 'npm-publish "npm-publish" "\
Invoke the compile mode with ARGS to publish an NPM package to a registry.

(fn &optional ARGS)" t)
(register-definition-prefixes "npm-publish" '("npm-publish-"))


;;; Generated autoloads from npm-run.el

(autoload 'npm-run "npm-run" "\
Invoke the compile mode with the run prefix-command and ARGS if provided.

(fn &optional ARGS)" t)
(register-definition-prefixes "npm-run" '("npm-run--"))


;;; Generated autoloads from npm-update.el

(autoload 'npm-update "npm-update" "\
Invoke the compile mode with the update prefix-command and ARGS if provided.

(fn &optional ARGS)" t)
(register-definition-prefixes "npm-update" '("npm-update--"))

;;; End of scraped data

(provide 'npm-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; npm-autoloads.el ends here
